### ISSUE TITLE
[BUG] Unable to Extract via iOS

### ISSUE THREAD

**Issue by mchist-cloud** [KnugiHK/WhatsApp-Chat-Exporter#102]
- WhatsApp version: 2.24.12.78 - iOS
- Platform: Windows
- Branch and version: main - 0.10.0

Traceback
```
c:\TEMP\working_wts>wtsexporter -i -b "C:\Temp\Backup\00008101-001465640208801E"
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Python\Python312\Scripts\wtsexporter.exe\__main__.py", line 4, in <module>
  File "C:\Python\Python312\Lib\site-packages\Whatsapp_Chat_Exporter\__main__.py", line 11, in <module>
    from Whatsapp_Chat_Exporter import ios_handler, ios_media_handler
  File "C:\Python\Python312\Lib\site-packages\Whatsapp_Chat_Exporter\ios_media_handler.py", line 12, in <module>
    from iphone_backup_decrypt import FailedToDecryptError
ImportError: cannot import name 'FailedToDecryptError' from 'iphone_backup_decrypt' (C:\Python\Python312\Lib\site-packages\iphone_backup_decrypt\__init__.py)

```

When attempting to export, the export does not occur.
The backup is an encrypted iOS backup. I know the passphrase, but did not have a prompt or flag to declare it.

1. Open CMD as admin
2. Run: wtsexporter -i -b "C:\Temp\Backup\00008101-001465640208801E"
3. See error

**Screenshots**
![ErrorCapture](https://github.com/KnugiHK/WhatsApp-Chat-Exporter/assets/173862676/be303315-fb4e-4e12-b275-692a98c94502)

Maybe I need to declare the passphrase in some fashion that i've missed? I've read through the instructions and attempted this setup on two different PC's.

**Comment by KnugiHK** [comment]
Oops... I did some breaking changes to the iphone_backup_decrypt dependency that do not compatible with the current release.

While waiting for the fix, you can install the latest WhatsApp-Chat-Exporter with the `dev` branch.

**Comment by mchist-cloud** [comment]
Thank you for the quick response KnugiHK.

I can confirm that the dev branch is allowing it to decrypt and extract now.

Much appreciated!

**Comment by KnugiHK** [comment]
I have rebased the iphone_backup_decrypt repository and the issue should be fixed now. Could you please try using the master branch of [KnugiHK/iphone_backup_decrypt](https://github.com/KnugiHK/iphone_backup_decrypt) and the main branch of the exporter to see if it works?

**Comment by mchist-cloud** [comment]
I uninstalled both and reinstalled via master and main branches. Can confirm that the exporter successfully decrypted an iOS backup.

**Comment by KnugiHK** [comment]
Thanks for your confirmation and report!
