### ISSUE TITLE
Encrypted backup (iphone)  sqlite3.OperationalError: no such table: Files

### ISSUE THREAD

**Issue by Desideratum11** [KnugiHK/WhatsApp-Chat-Exporter#104]
Back up is encrypted and i followed instruction and installed 

pip install git+https://github.com/KnugiHK/iphone_backup_decrypt 

prior to running the extractor. Unsure if there are extra steps that i need to take in order to decrypt? Instruction on the decryptor werent too elaborate 
![Untitled](https://github.com/KnugiHK/WhatsApp-Chat-Exporter/assets/174492818/ba632ae9-a801-4eca-ab02-b80a9efb9adc)

**Comment by KnugiHK** [comment]
Hi. Is your specified path point to an iOS full backup?

**Comment by Desideratum11** [comment]
Yes. I downloaded it from icloud on mac and transferred the entire folder over to my windows computer.

**Comment by KnugiHK** [comment]
What's your iOS version?

**Comment by Desideratum11** [comment]
ios17 do you need specific number?

**Comment by Desideratum11** [comment]
Im sorry. Its on 16.1.1

**Comment by KnugiHK** [comment]
Can you open the Manifest.db of the backup and post the database schema here?

**Comment by Desideratum11** [comment]
the Manifest.db file shows at a 0kb empty database with tables, indices, views, and triggers all showing 0

**Comment by Desideratum11** [comment]
the only unencrypted file in the backup itself (done about an hour ago) is Backup.plist but no .db file other than the empty manifest

**Comment by KnugiHK** [comment]
I guess there is no Manifest.db file in your downloaded backup and the file is actually created by the exporter.

I've never tried downloading a backup from iCloud, so there might be significant differences between iCloud backups and those created locally using iTunes or Finder. In simple terms, the exporter may not support iCloud-downloaded backups. I'm not entirely sure about this, but I may look into it later.

**Comment by Desideratum11** [comment]
i figured as much haha. you can close this then. If i manage to back it up unencrypted do you think that would work?

**Comment by KnugiHK** [comment]
> i figured as much haha. you can close this then. If i manage to back it up unencrypted do you think that would work?

The best way to do it is by backing up your phone with macOS's Finder or iTunes on Windows. Encrypted or not should not matters as long as you do it with the mentioned tools.
