### ISSUE TITLE
[FEATURE] Adding Whatsapp-like .txt export method with media

### ISSUE THREAD

**Issue by AlexanderHartz** [KnugiHK/WhatsApp-Chat-Exporter#108]
I've loved this tool so much, it has made my life a lot easier, but there is a certain feature I need and I can't find anywhere. It's the posibility to export txt files like the ones from More/ Export Chat in Whatsapp.

Maybe it sounds a little dumb to ask for such a simple format, but I need it only because that format is compatible with Telegram and I'd love to export all of my important Whatsapp chats to Telegram with all of the media included by using this incredible tool, because Whatsapp only allows a few media and a few chats in their exports. The only thing that is missing is the feature to export Whatsapp-like txt files, because the feature to separate the media by chats is already there.

I know there are options like Whatsapp Viewer to export txt files but I don't know whether they are similar to the Whatsapp's ones and I can´t find it out because it can´t open the new schema.

I'd love to see this feature working. Thank you for reading

**Comment by KnugiHK** [comment]
The basic of the format has been implemented in a83c8eb. You may try that in the `dev` branch. Expect bugs since it is a quick implementation.

**Comment by KnugiHK** [comment]
Released in 0.10.5. If there is any problems on this feature, please open a new issue.
