### ISSUE TITLE
Latest versions of WhatsApp on iOS do not contain ContactsV2.sqlite[BUG]

### ISSUE THREAD

**Issue by ReclusiveEagle** [KnugiHK/WhatsApp-Chat-Exporter#109]
The latest version of WhatsApp on iOS does not contain a ContactsV2.sqlite resulting in:
`Contact database not found.`

My last backup of my WhatsApp chats was around 2023 and there were no issues. Luckily I've archived multiple different iTunes backups over the last few months. Testing these backups I am able to extract chats before my 1 May 2024 backup.

In my 2023 backup, ContactsV2.sqlite exists in the **AppDomainGroup-group.net.whatsapp.WhatsApp.shared** folder.
![2023](https://github.com/user-attachments/assets/26ec18c8-2148-41cb-829d-50a1a540c85d)

All backups post 1 May 2024 do not contain ContactsV2.sqlite. I've also attempted a manual search of all files in the entire unencrypted backup and ContactsV2.sqlite does not exist period. Does anyone know if WhatsApp has moved to a different database or where it is located?
![2024](https://github.com/user-attachments/assets/e729b249-b0f5-45f7-b3b7-4c0961376a93)

**Comment by ReclusiveEagle** [comment]
Seems to be the same issue reported [here](https://github.com/KnugiHK/WhatsApp-Chat-Exporter/issues/107)

**Comment by ReclusiveEagle** [comment]
### Update

New hash seems to be _0618655a1de1254eca90c229002cdea325de408d_

`0618655a1de1254eca90c229002cdea325de408dAppDomainGroup-group.net.whatsapp.WhatsApp.sharedMessage/Media/[Contact Number]@s.whatsapp.net/0/6/06693485-42bb-4f27-844d-1c37d93c1291.opusbplist00`

**Comment by userTeki** [comment]
Will there be an update fixing this?

**Comment by KnugiHK** [comment]
Closing as a duplication of #107.
