### ISSUE TITLE
[BUG] URL generation bug, plus WORKAROUND

### ISSUE THREAD

**Issue by code-consensus** [KnugiHK/WhatsApp-Chat-Exporter#113]
- WhatsApp version: any
- OS: Android
- Platform: any
- Branch and version: 0.10.0

**Describe the bug**
The program makes URLs clickable as per #69 . However, there is a bug of sorts involving messages that involve new-lines inside the message, where the link includes text and `<br>` elements.

**To Reproduce**
1. With a message like:
"https://example.com/webpage.html
Hey check out this link"
2. the generated HTML will look like: 
`<a href="https://example.com/webpage.html<br>Hey" target="_blank">`

3. The same if there are two-new lines, you would get html like `<a href="https://example.com/webpage.html<br><br>Hey">`

**Workaround**
The issue is caused by the `<br>` insertions in the `if "\r\n" in msg:` and `if "\n" in msg:` sections in android_handler.py ([line 446](https://github.com/KnugiHK/WhatsApp-Chat-Exporter/blob/b34045a59fcd4da40c1021def34415039b789f8b/Whatsapp_Chat_Exporter/android_handler.py#L446) and [461](https://github.com/KnugiHK/WhatsApp-Chat-Exporter/blob/b34045a59fcd4da40c1021def34415039b789f8b/Whatsapp_Chat_Exporter/android_handler.py#L461)).

If you comment out those code segments to NOT add `<br>`, then the URLs are handled correctly (e.g. `<a href="https://example.com/webpage.html">`). **However, that is at the expense of not creating a new line.**

There must be some incompatibility with the addition of the `<br>` elements to the message and the subsequent "urlification" of the message in create_html() (the urlize() function in whatsapp.html?)

**Comment by KnugiHK** [comment]
The issue should be resolved in commit f35bf24 by adding a space before the `<br>` tag, although it is essentially an alteration to the message.

To (if) any forensic investigators: please use the god damn paid tools like EnCase and FTK or whatever.

**Comment by code-consensus** [comment]
I tested this myself, and seems to work perfectly now. As for the message being slightly "altered", that is a small price to pay to have the message show up correctly!

> The issue should be resolved in commit [f35bf24](https://github.com/KnugiHK/WhatsApp-Chat-Exporter/commit/f35bf24a5eb1ba942c4d9f53f16f5e769ca488cc) by adding a space before the `<br>` tag, although it is essentially an alteration to the message.
> 
> To (if) any forensic investigators: please use the god damn paid tools like EnCase and FTK or whatever.
