### ISSUE TITLE
[BUG] split HTML ouput misses the final message in chat

### ISSUE THREAD

**Issue by code-consensus** [KnugiHK/WhatsApp-Chat-Exporter#114]
- WhatsApp version: 2.24.06.77
- OS: Android
- Platform: Windows
- Branch and version: 0.10.0

**Describe the bug**
With the "--split" command-line option, the program splits up larger chats. In ALL the generated chats, including ones that are NOT split up, the final message is missing.

**To Reproduce**
1. run wtsexporter _without_ "--split"
2. open an HTML chat file and scroll down to see the final message (either from "You" or the contact). 
3. run wtsexporter _with_ "--split"
4. open the very same chat in the new output folder. Scroll down to see the final message and you will see the last message is not there. This affects ALL output files, not just the ones that were split up.

The issue is in create_html() under the "[if maximum_size is not None](https://github.com/KnugiHK/WhatsApp-Chat-Exporter/blob/b34045a59fcd4da40c1021def34415039b789f8b/Whatsapp_Chat_Exporter/android_handler.py#L766)" section, but I can't seem to figure out what the problem is.

**Comment by KnugiHK** [comment]
The issue should be fixed in e268484.

**Comment by code-consensus** [comment]
I tested this, and it seems to work perfectly now -- thanks! I tested with, and without, the --split option, and for _non-split_ files, their hashes were identical. And on the the split files, from the chats that I at least recognized, seems to also work.

> The issue should be fixed in [e268484](https://github.com/KnugiHK/WhatsApp-Chat-Exporter/commit/e2684845b8cc8b09760bc480549801859cd97406). You can try the `dev` branch to see if the problem persists or if other problems come out.

**Comment by KnugiHK** [comment]
Released in 0.10.5.
