### ISSUE TITLE
[FEATURE] show call logs in minutes and MB rather than seconds and bytes

### ISSUE THREAD

**Issue by code-consensus** [KnugiHK/WhatsApp-Chat-Exporter#115]
**Is your feature request related to a problem? Please describe.**
The current call logs output shows the calls in seconds and bytes transferred. ([line 733 in android_handler.py](https://github.com/KnugiHK/WhatsApp-Chat-Exporter/blob/b34045a59fcd4da40c1021def34415039b789f8b/Whatsapp_Chat_Exporter/android_handler.py#L733)). This is okay for a very short call of a few seconds, but for anything over a minute the numbers become quite large for readability ("lasted for 2467 seconds with 14943115 bytes transferred")

**Describe the solution you'd like**
Show the calls in minutes and megabytes.
e.g. "lasted for 41:07 minutes with 14.250 MB transferred"

**Comment by KnugiHK** [comment]
Implemented in 8fcd50d & 8ffa8cf.

**Comment by KnugiHK** [comment]
Released in 0.10.5.
