### ISSUE TITLE
impossible to create a file it already exists

### ISSUE THREAD

**Issue by kintaro1981** [KnugiHK/Whatsapp-Chat-Exporter#14]
Hello and thank you for your work!

I'm getting this error, now:

c:\Users\MYUSER\Desktop\PARA\1_Progetti\wabackup\working_wts>wtsexporter -i -b "C:\Users\MYUSER\AppData\Roaming\Apple Computer\MobileSync\Backup\MYID"
Traceback (most recent call last):
  File "C:\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Python310\Scripts\wtsexporter.exe\__main__.py", line 7, in <module>
  File "C:\Python310\lib\site-packages\Whatsapp_Chat_Exporter\__main__.py", line 157, in main
    extract_iphone_media.extract_media(options.backup)
  File "C:\Python310\lib\site-packages\Whatsapp_Chat_Exporter\extract_iphone_media.py", line 118, in extract_media
    os.mkdir(destination)
FileExistsError: [WinError 183] Impossibile creare un file, se il file esiste già: 'Message/Media/393471478055-1354147243@g.us/A'

"Impossibile creare un file, se il file esiste già" means: "Impossible to create a file, it already exists"

**Comment by KnugiHK** [comment]
Before you run the script, is "Message/Media/393471478055-1354147243@g.us/A" exist?

**Comment by kintaro1981** [comment]
no, the working_wts directory is empty

**Comment by KnugiHK** [comment]
Could you try to add a condition ``` and not os.path.isdir(destination)``` in to line 117 of extract_iphone_media.py and see if it works?
From
```python
if flags == 2:
    os.mkdir(destination)
elif flags == 1:
    shutil.copyfile(f"{base_dir}/{folder}/{hashes}", destination)
```
To
```python
if flags == 2 and not os.path.isdir(destination):
    os.mkdir(destination)
elif flags == 1:
    shutil.copyfile(f"{base_dir}/{folder}/{hashes}", destination)
```

**Comment by kintaro1981** [comment]
It worked. 👍

**Comment by KnugiHK** [comment]
Fixed. I will leave this open until next release

**Comment by KnugiHK** [comment]
Released: https://github.com/KnugiHK/Whatsapp-Chat-Exporter/releases/tag/0.8.5
