### ISSUE TITLE
link to not supported files

### ISSUE THREAD

**Issue by kintaro1981** [KnugiHK/Whatsapp-Chat-Exporter#15]
Hello,

I saw the notice if an attachment is not supported (example PDF).

`The file cannot be displayed here, however it should be located at <<path>>`

How about add to the notice a relative local link to that file so at least is a click away from being opened?

Avoiding in this way to copy and past the path or find it manually.

**Comment by KnugiHK** [comment]
Please check the referenced commit in this issue. Do you think adding a link suit your needs?

**Comment by KnugiHK** [comment]
Released: https://github.com/KnugiHK/Whatsapp-Chat-Exporter/releases/tag/0.8.5
