### ISSUE TITLE
I have a different goal - how could I reuse this software?

### ISSUE THREAD

**Issue by lmarceg** [KnugiHK/Whatsapp-Chat-Exporter#18]
Hi, 
I bought an iPhone SE 2022 for my daughter but when I did the migration from Android to iPhone with the iOS data migrator tool, WhastApp wasn't transferred at all. I tried twice, with no luck. I therefore downloaded and purchased AnyTrans, which actually moved WA DB from Android to iPhone, but I see that all the WA pictures are shown in Photos with the date of the transfer and not with the date of when they were received originally.
Since there are thousand of pictures, I cannot manually change the timestamp in Photos, so I was thinking of taking the DB from the iPhone backup, and change the timestamp within the DB - I hope the timestamp of the message and of the image are stored there.
If I can do this job succesfully, I would then need to resend this file to the iPhone, and I wonder:

1) do you know the DB structure of WA, so that I can check in advance if I can change the timestamp?
2) How can I send the DB back to the iPhone?

Thanks!
Luca

**Comment by KnugiHK** [comment]
Hmmm... seems fun to accomplish what you want to do!

1. Are you asking for the structure for iOS or Android?
2. I have never done that, but jailbreak (which doesn't seems to make sense in your situation), or replacing the DB in an iPhone backup may do the trick.

**Comment by lmarceg** [comment]
For iOS

But I may have found an iPhone backup extractor, so probably I will try using that, and then I’ll play with MySQL to see if there are some tables that may be useful

 

Your program does 100 times more than what I need

I also hope that replacing the DB will do the trick and the iPhone will get it, but I have to try (with Apple, you never know)

 

Thanks

Luca

**Comment by KnugiHK** [comment]
Good luck with your hack!
