### ISSUE TITLE
 feature request: export 64-digit encryption key

### ISSUE THREAD

**Issue by privnote42** [KnugiHK/Whatsapp-Chat-Exporter#20]
Hello,
I have a feature request.
Would it be possible to output / export the 64-digit encryption key so that I can import an E2E encrypted backup?

This is the use case:
I forgot my password for the E2E encrypted backup and did not save the 64-digit encryption key.

I wanted to update my phone to a new LineageOS version, so I backed up Whatsapp and then deleted all partitions.
I also made a backup of the Whatsapp folder in /data/data, so I still have encrypted_backup.key as a file.

The export also works without problems, but unfortunately Whatsapp does not seem to accept this non-encrypted database; at least when I reinstalled Whatsapp, I was not offered a restore with it.

**Comment by KnugiHK** [comment]
Hi. Do you mean provide a way to parse the encryption key and show the key in hex form?

**Comment by privnote42** [comment]
Hi, yes the output in the same form as you have to enter the key when restoring in whatsapp, i.e. as a 64-digit hex code.

**Comment by KnugiHK** [comment]
I add an option (-s) to the CLI for showing the hex key. I don't have the next release plan for now. You can check it out by installing the exporter with the follow command:
`pip install git+https://github.com/KnugiHK/Whatsapp-Chat-Exporter.git@dev`

**Comment by privnote42** [comment]
is working, thank you very much

**Comment by KnugiHK** [comment]
I will leave it open until the feature is being released

**Comment by KnugiHK** [comment]
Hi @velecto1, could you please report the problem with the -s option in this issue in detail?

**Comment by KnugiHK** [comment]
This feature is only available in dev or message_table branch for now, and will not be released before new schema support is released.

**Comment by KnugiHK** [comment]
Released in [0.9.0](https://github.com/KnugiHK/Whatsapp-Chat-Exporter/releases/tag/0.9.0).
