### ISSUE TITLE
[Request] Format the already exported chat as txt

### ISSUE THREAD

**Issue by Drjacky** [KnugiHK/WhatsApp-Chat-Exporter#22]
I have the decrypted chat as txt (I already exported it from More -> Export Chat).
Is it possible to allow to have this result:
![image](https://user-images.githubusercontent.com/2296754/197386292-6afc384b-9970-4bf5-8861-b01272563902.png)
by input that plain text?

**Comment by KnugiHK** [comment]
You mean reading the export txt file and produce a HTML page like what this exporter does?

**Comment by Drjacky** [comment]
Yes

**Comment by KnugiHK** [comment]
Sure. I will look into it.

**Comment by KnugiHK** [comment]
> > Sure. I will look into it.
> 
> I wish it is .txt too. Anyway, is it possible you pack the python script become executable (.exe)? it will be more convenient

Agree, let's move the discussion of making executable to #29.

**Comment by KnugiHK** [comment]
I implemented the feature in 0897dc2. Feel free to try it in the `dev` branch and report any issues.

**Comment by KnugiHK** [comment]
Released in 0.9.5.
