### ISSUE TITLE
HTML file does not load fully.

### ISSUE THREAD

**Issue by newdrkhckr** [KnugiHK/WhatsApp-Chat-Exporter#23]
I tried to open one of created HTML file in Google Chrome. HTML file size is around 100 mb. But seems like Chrome cant handle to open that file. 

I tried multiple times and i recieved 'Out of Memory' and 'SBOX_FATAL_MEMORY_EXCEEDED' errors from chorme. It exceeds 12 GB ram useage when trying to open HTML file. 

Also i tried to not include any whatsapp image media in HTML file with deleting Whatsapp Images directory. But I get same result still HTML file does not fully loads.

Are there any solution for this ?

**Comment by newdrkhckr** [comment]
UPDATE:

I tried other than chromium based browsers and it seems to open files that chromium based ones cant handle.
Mozilla firefox seems to have working.

**Comment by KnugiHK** [comment]
How many messages does your chat have?

Maybe we can add an option for users to choose splitting the result HTML?

**Comment by newdrkhckr** [comment]
> How many messages does your chat have?
> 
> Maybe we can add an option for users to choose splitting the result HTML?

Around 250k messages and 1k media file on one single chat. It would be great to have option for splitted outputs if possible.

**Comment by velecto1** [comment]
Hi, I just want to double-check. Is this option already implemented? I suppose not, as I don't see it among new commits.

**Comment by KnugiHK** [comment]
It is not yet implemented. I just forgot to reopen this issue.

**Comment by KnugiHK** [comment]
I implemented the splitting feature. Feel free to try it in the `dev` branch and report any issues.

Note that the size is not the exact limit but a rough limit. The actual output size may exceed the limit.

**Comment by KnugiHK** [comment]
Released in 0.9.5.
