### ISSUE TITLE
Media is not supported

### ISSUE THREAD

**Issue by Amitef123** [KnugiHK/Whatsapp-Chat-Exporter#27]
it seems like all my media/data files are not supported.
I try to extract media from unencrypted iphone backup, the media folder is extracted and there is access to the media.
but the html files don't any media or link path for the media.
(the backup date is 03.2022)

**Comment by KnugiHK** [comment]
Are you working on Windows/Linux/MacOS?

**Comment by UsamaAshfaq** [comment]
@KnugiHK I second that media (images,Voice notes) is not supported in html (Screenshot Attached )

![git hub whatsapp](https://github.com/KnugiHK/Whatsapp-Chat-Exporter/assets/37629118/c3e549e3-5b96-4fcb-8306-f35064034f9f)

**Comment by KnugiHK** [comment]
@UsamaAshfaq Can you show me the working directory structure and the command issued?

**Comment by UsamaAshfaq** [comment]
@KnugiHK Sure. Command issued is : wtsexporter -a and working directory's SS is attached.
![working dir whatsapp](https://github.com/KnugiHK/Whatsapp-Chat-Exporter/assets/37629118/75a83429-95ec-48b1-9bf2-5e1cae85de89)

**Comment by KnugiHK** [comment]
The `Media` folder should be inside the `WhatsApp` directory. This is because users are assumed to copy the whole WhatsApp directory from their shared storage directly.

**Comment by UsamaAshfaq** [comment]
It worked. I was looking for a way, to view my old backed up data on pc for more than 2 months. and now I am able to, thanks to you. Thank you very much ❤️
