### ISSUE TITLE
Add to common offsets "The offsets of your IV and database are 67 and 193, respectively"

### ISSUE THREAD

**Issue by gsriram88** [KnugiHK/Whatsapp-Chat-Exporter#32]
Hello,

Thank you for a great tool. It works perfectly for me.

While decrypting, I get this "The offsets of your IV and database are 67 and 193, respectively. To include your offsets in the program, please report it by creating an issue on GitHub: https://github.com/KnugiHK/Whatsapp-Chat-Exporter/issues/new". It succeeded in brute forcing and continued fine.

Thanks!

**Comment by KnugiHK** [comment]
Thanks for the report, it will be added in the next release.

**Comment by KnugiHK** [comment]
Released in [0.9.0](https://github.com/KnugiHK/Whatsapp-Chat-Exporter/releases/tag/0.9.0).
