### ISSUE TITLE
See only media (photos, videos, gif, audio etc.) in the html and no text conversations

### ISSUE THREAD

**Issue by gsriram88** [KnugiHK/Whatsapp-Chat-Exporter#33]
Hi there,

Is there a way to quickly process the resultant html so that all the normal conversation text is removed, and only the media (such as photos, videos, gif, audio etc.) alone is present? I basically want something like the "Media, links, and docs" feature of the original WhatsApp app where one can quickly scroll up and down the media alone.

I no longer have the decrypted DB handy, so I am looking for a way to post process your result html and strip away the text and keep only the media. Is there a quick way/hack to do this?

WhatsApp failed to restore my DB and this tool has been great at retrieving my memories in a coherent way! Thanks a lot for your work!

**Comment by KnugiHK** [comment]
As there is no attribute to tell if there are any media, I quickly created a JavaScript code to remove any rows that do not have the following tags: img, audio, video.
```javascript
const elems = [...document.getElementsByClassName("table")[0].children]
elems.forEach((elem) => {
	if (elem.getElementsByClassName("w3-center").length <= 0) {
		search = elem.querySelector(".w3-col.m10.l10");
		if (search.querySelectorAll("img,audio,video").length <= 0){
			elem.remove();
		};
	}
});
```
After executing the above code in the console, you may save the page into a single file with an extension or convert the above code to some program to remove the unwanted elements for you. 

Note that the code will not remove all text-only messages to preserve the conversation date.
