### ISSUE TITLE
Offset reporting and FileNotFoundError

### ISSUE THREAD

**Issue by oberkut** [KnugiHK/WhatsApp-Chat-Exporter#38]
Decryption key specified, decrypting WhatsApp backup...
Common offsets are not applicable to your backup. Trying to brute force it...
The offsets of your IV and database are 67 and 193, respectively. To include your offsets in the program, please report it by creating an issue on GitHub: https://github.com/KnugiHK/Whatsapp-Chat-Exporter/issues/new
Traceback (most recent call last):
  File "/home/berkut/.local/bin/wtsexporter", line 8, in <module>
    sys.exit(main())
  File "/home/berkut/.local/lib/python3.10/site-packages/Whatsapp_Chat_Exporter/__main__.py", line 124, in main
    error = extract.decrypt_backup(db, key, msg_db, crypt)
  File "/home/berkut/.local/lib/python3.10/site-packages/Whatsapp_Chat_Exporter/extract.py", line 170, in decrypt_backup
    with open(output, "wb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'msgstore.db'

**Comment by KnugiHK** [comment]
Hi. Could you provide the command you entered?

**Comment by oberkut** [comment]
wtsexporter -a -k key -b msgstore.db.crypt14

**Comment by KnugiHK** [comment]
Not sure if your problem is related to https://stackoverflow.com/q/18758673/9478891 or https://stackoverflow.com/q/2401628/9478891. Try to specify another location for the database file with this command: `wtsexporter -a -k key -b msgstore.db.crypt14 -d /tmp/temp.db`

**Comment by KnugiHK** [comment]
The offset is included in the 0.9.5 release.

**Comment by KnugiHK** [comment]
Since the code is being refactored, the stack trace and the bug reported here may no longer be valid. For now, I will be closing this issue. If anyone encounters a similar problem with the latest version, please feel free to open a new issue.
