### ISSUE TITLE
Is there a virus in the Hot Fix 2023/05/17 release?

### ISSUE THREAD

**Issue by Lehnemann** [KnugiHK/WhatsApp-Chat-Exporter#43]
I don't know much about your code but Bitdefender warns me and I throw the exe file in virustotal.com and It said this to me...
![image](https://github.com/KnugiHK/Whatsapp-Chat-Exporter/assets/2759337/1b5f32e7-261a-442f-8992-1a3ef7d72c50)

Is it a false positive?

**Comment by KnugiHK** [comment]
It is probably a false positive.

I compile the program with [Nuitka in GitHub Action environment](https://github.com/KnugiHK/Whatsapp-Chat-Exporter/actions/runs/4994277006). A Python program packed/compiled into a binary is always easily detected as a virus. I checked some issues on Nuitka. Compiling the thing right without being falsely detected is behind their paywall.

I also checked the result from VirusTotal, no detection on Linux and MacOS binaries. Most of the threat detected in Windows's binary is "Lazy", and the sandbox analysis seems fine to me, with no evidence of the binary getting infected by other viruses.

The compiling is done automatically in GitHub Action. To further prevent tampering on the binaries after they are downloaded from the Artifact, I told the workflow to calculate the SHA256 checksum right after the binary is compiled ([see commit](https://github.com/KnugiHK/Whatsapp-Chat-Exporter/commit/bf06795962cdc6ebdc2e052cf68a03292218ebe2)). The hash will then [displayed in the workflow](https://github.com/KnugiHK/Whatsapp-Chat-Exporter/actions/runs/4994331794/jobs/8944741132#step:5:45). This (some kind of) security measure will goes into effect starting from next release.

Anyway, when in doubt, you can always review the code (which I always encourage people to do so before using someone else's software) and install the exporter with `pip install .`.

**Comment by Lehnemann** [comment]
Thanks.
