### ISSUE TITLE
Wrong media directory name?

### ISSUE THREAD

**Issue by kintaro1981** [KnugiHK/WhatsApp-Chat-Exporter#49]
I'm using the "dev version".

with:
`wtsexporter -i -b /Users/<USERNAME>/Library/Application\ Support/MobileSync/Backup/<ID>/`

it creates these directories:

- results
  - Message
    - Media
    - vCards
- Message
  - Media
  - vCards

But the HTML file inside results directory refer to Whatsapp directory and not Message directory so no media content (audio/photo/video) are displayed. Renaming Whatsapp in Message solve the problem.

Example:
`<img src="WhatsApp/Avatars/39334826789-1451324297@g.us.j" onerror="this.style.display='none'">`

Is this a bug or I done something wrong?

**Comment by KnugiHK** [comment]
It is a bug and was introduced in #25.

**Comment by KnugiHK** [comment]
Should be fixed with ed658d7. You can pull the change and try again to see if it is fixed.

**Comment by kintaro1981** [comment]
> You can pull the change and try again to see if it is fixed.

Yes I confirm is fixed now.

I updated my dev install with:
`pip uninstall Whatsapp-Chat-Exporter `
`pip install git+https://github.com/KnugiHK/Whatsapp-Chat-Exporter.git@dev`
is there another more direct way?

**Comment by KnugiHK** [comment]
Does `-U --force-reinstall` helps? `pip install -U --force-reinstall git+https://github.com/KnugiHK/Whatsapp-Chat-Exporter.git@dev`.

**Comment by KnugiHK** [comment]
Released in 0.9.5.
