### ISSUE TITLE
Recreate HTML from an already exported db

### ISSUE THREAD

**Issue by kintaro1981** [KnugiHK/Whatsapp-Chat-Exporter#50]
Is it possibile to run wtsexporter over an already exported backup?

I would like to re-create the HTML in the future when new features are going to be implemented.

**Comment by KnugiHK** [comment]
Do you mean run the wtsexporter over an output HTML file or the database?

**Comment by kintaro1981** [comment]
I mean:
I run wtsexporter once and then run it again to re-create htmls without the need of the original iPhone backup.

**Comment by KnugiHK** [comment]
You can keep the `Message` folder and the database file `7c7fba66680ef796b916b067077cc246adacf01d`. Then, run the exporter again without `-b`: `wtsexporter -i`.
