### ISSUE TITLE
Very long vCards filenames

### ISSUE THREAD

**Issue by kintaro1981** [KnugiHK/WhatsApp-Chat-Exporter#51]
Hello,
I noticed during my nextcloud sync that some vCards filename is very long (NC can't sync files with filename > of 250 characters).

Is it possibile to trim the filenames? If the filenames are needed this long can I delete some vCards?
Am I going to break something in html chats?

**Comment by KnugiHK** [comment]
Hmm, I already tried to limit the file name to < 250 characters. Perhaps the limit should be further reduced?

If you delete the vCards file, it will not break anything in the HTML.

**Comment by KnugiHK** [comment]
The new limit to the vCard file name is released in 0.9.5.

**Comment by duracotton** [comment]
@KnugiHK Still an open problem as the vcard target path length is important, not the vcard file name length alone.
If the target path length of the vcard is > 256 chars the tool still throws an error on Windows. So the tool should be aware what the base path is and its length and then substract it from 256 so you know what the allowed max vcard file name is.

**Comment by KnugiHK** [comment]
Once I confirm the problem mentioned by @duracotton, I will reopen this issue.
