### ISSUE TITLE
Quotation support

### ISSUE THREAD

**Issue by duracotton** [KnugiHK/WhatsApp-Chat-Exporter#57]
Hi there,
currently the output html is already supporting direct links to a cited message.
I'd like to suggest the feature to also show the cited message itself as we know it from Whatsapp. 
Is there any html support for re-using/displaying already existing DOM element (the original / cited message) instead of having to creating a copy of the message's value and icnreasing the html's file size? Is "href" doing the job?

**Comment by KnugiHK** [comment]
Are you working on iOS? The quotation feature is implemented already in Android and is planned for iOS.

As for reusing DOM, I will see if it is feasible.

**Comment by duracotton** [comment]
Yes, I used the tool to export chats from an iOS whatsapp backup. That's nice to hear :)

**Comment by KnugiHK** [comment]
Meanwhile, you can use `--size` to prevent the HTML file size from becoming too large.

**Comment by KnugiHK** [comment]
The only way to reuse DOMs I know is through Javascript. However, I want to avoid adding Javascript to the template. Hence, it may not be feasible under this circumstance. If anyone knows how to do it without Javascript, comments are welcome.

**Comment by KnugiHK** [comment]
Moving the discussion of quotation to #28.
