### ISSUE TITLE
iOS messages on a specific day erroneously have the same time in html

### ISSUE THREAD

**Issue by juliuspfadt** [KnugiHK/WhatsApp-Chat-Exporter#64]
I exported a WhatsApp chat from my iphone backup, and when looking at the html, all times for a chat on a specific day are equal, when in truth they are not.

**Comment by KnugiHK** [comment]
Do you meant inside the chat, only messages on a specific day have the same time, but the rest of the messages in the chat have the correct times?

**Comment by juliuspfadt** [comment]
no, for a single chat, for each day, all the messages have the same time. None of the messages have the correct time, only the correct date. Although I assume that maybe always the first message of a day has the correct time

**Comment by LoSunny** [comment]
Yes this indeed solve the issue. Also, is there a way for us to adjust the timezone? By default it seems to assume GMT, can we set hour own timezone or used the computer timezone as default?

**Comment by juliuspfadt** [comment]
I actually found that the timestamps are not always in the correct order when extracted from the database. I had them printed in seconds, and it was evident why the messages would be not in chronological order. I added a few lines that would make sure they were in ascending order to the code, and that fixed the issue for me.

**Comment by KnugiHK** [comment]
> That fixes the issue yes. But I also found that the timestamps are not always in the correct order when extracted from the database. I had them printed in seconds, and it was evident why the messages would be not in chronological order. I added a few lines that would make sure they were in ascending order to the code, and that fixed the issue for me.

Thanks for pointing out the problem. Does adding `ORDER BY timestamp ASC` (Android) and `ORDER BY ZMESSAGEDATE ASC` (iOS) to the SQL query solve the problem?

**Comment by juliuspfadt** [comment]
I only know about the iOS solution, and yes, that solves the problem.

**Comment by KnugiHK** [comment]
I will leave this open until next release.

**Comment by KnugiHK** [comment]
Released in 0.10.0.
