### ISSUE TITLE
sqlite3.DatabaseError: database disk image is malformed

### ISSUE THREAD

**Issue by yonka2019** [KnugiHK/WhatsApp-Chat-Exporter#66]
another wa exporters works properly, why this throws this issue?

**Comment by yonka2019** [comment]
`wtsexporter_x64.exe -a
Gathering contacts...(446)
Traceback (most recent call last):649)
  File "C:\Users\yonka\AppData\Local\Temp\ONEFIL~3\__main__.py", line 287, in <module>
  File "C:\Users\yonka\AppData\Local\Temp\ONEFIL~3\__main__.py", line 240, in main
  File "C:\Users\yonka\AppData\Local\Temp\ONEFIL~3\Whatsapp_Chat_Exporter\extract.py", line 380, in messages
sqlite3.DatabaseError: database disk image is malformed`

**Comment by yonka2019** [comment]
what really strange, is that the DB Browser open the messages column in msgstore.db without any issues

**Comment by KnugiHK** [comment]
From what I understand, for now, it doesn't seem to be the problem of the exporter itself. I can't really tell why it would happen as I don't have your database file. But if you don't mind, you can send me the database for inspection.

In the meantime, you may try [this](https://www.data-recovery-solutions.com/blog/sqlite-database-disk-image-is-malformed/). Just remember to do a backup for your database.

PS. Could you run the exporter with `pip install` (i.e., not using the binary)? That should give a more verbose traceback for debugging.
