### ISSUE TITLE
WhatsApp database not found.

### ISSUE THREAD

**Issue by keiranlovett** [KnugiHK/WhatsApp-Chat-Exporter#70]
I get `WhatsApp database not found.` when running on iOS. To my knowledge I have a WhatsApp database, I see in my latest iCloud backups 5gb for WhatsApp and I have my database there.

Can you provide more context in the warning so it is easier to troubleshoot?

**Comment by KnugiHK** [comment]
Hi. Can you show me the command your issued?

**Comment by italohdc** [comment]
I have the same issue. I'm using a non-encrypted backup for that.

The command I used:
```sh
wtsexporter -i -b path/to/backup
```

**Comment by KnugiHK** [comment]
> I have the same issue. I'm using a non-encrypted backup for that.
> 
> The command I used:
> 
> ```shell
> wtsexporter -i -b path/to/backup
> ```

Do you see this file `7c7fba66680ef796b916b067077cc246adacf01d` in the backup directory?

**Comment by keiranlovett** [comment]
> Hi. Can you show me the command your issued?

`wtsexporter -i -b ~/Library/Application\ Support/MobileSync/Backup/00008101-001318860CA0001E/`

**Comment by keiranlovett** [comment]
#55 was able to point me in the right direction. Can close
