### ISSUE TITLE
Recent groups - Not showing correct contact data

### ISSUE THREAD

**Issue by txanetxarra** [KnugiHK/WhatsApp-Chat-Exporter#71]
Hi KnugiHK ,

First of all, congratulations for the WhatsApp-Chat-Exporter.

I've been playing around with it today and I have identified a bug on the program.  I've converted my personal Whatsapp DB today, and I've noticed that, in the groups created during the last year, the conversion shows the name of the group for all messages sent by all members.  As an example attached a screenshot of the group "Sorpresa!".

As you can see, the messages sent by all members are labeled as "Sorpresa!", and so, it's impossible to identify the sender.

This is happening either using or not the contacts database wa.db file.

I've also noticed that the html file name of the defective groups starts with some numbers.  For example, for this group the file name is: "120363026294026347-Sorpresa .html".

For a group that correctly shows the sender nubmers / names, the file is, for example: "GroupName.html".

Also, I've been able to correctly export my messages for these groups with the "whatsapp-exporter" python tool, although this tool is not able to include media in the exported chats (https://github.com/chrrel/whatsapp-exporter).

I hope this information helps to improve the tool.

![imagen](https://github.com/KnugiHK/WhatsApp-Chat-Exporter/assets/107510800/394f602f-c24c-4385-8c4c-54e4b59a1cd6)

**Comment by KnugiHK** [comment]
Duplication of #67. Neverthless, thanks for your detailed information.
