### ISSUE TITLE
exporting chats more then i actually had 

### ISSUE THREAD

**Issue by mian196** [KnugiHK/WhatsApp-Chat-Exporter#74]
I used this tool before it worked perfectly but this time, it created around 4k chats, i tried opening some but they were empty and less than 10kb in size, is this an error, or I'm the only one facing this issue

**Comment by KnugiHK** [comment]
Hi. Can you provide a screenshot on one of the empty chat?

**Comment by mian196** [comment]
![image](https://github.com/KnugiHK/WhatsApp-Chat-Exporter/assets/74845621/0de51cae-68dd-4802-bb8d-ed106a029cbe)
![image](https://github.com/KnugiHK/WhatsApp-Chat-Exporter/assets/74845621/5ca22762-6bad-4a93-b613-32859fbb5f28)

**Comment by mian196** [comment]
sorry for late , i provided the ss of empty chats

**Comment by mian196** [comment]
![image](https://github.com/KnugiHK/WhatsApp-Chat-Exporter/assets/74845621/a24f24e8-87e8-4187-bda2-d9a14e573995)

**Comment by KnugiHK** [comment]
Hi. That should probably fine and is expected. But I think we can add a logic to prevent no message chats being exported.

**Comment by KnugiHK** [comment]
Merging this issue to #112 as it is much more comprehensive.
