### ISSUE TITLE
[BUG] Not supported WhatsApp internal message

### ISSUE THREAD

**Issue by mruepp** [KnugiHK/WhatsApp-Chat-Exporter#90]
- WhatsApp version: 2.24.5.73 - iOS
- Platform: MacOS
- Branch and version: main

**Describe the bug**
I did an Iphone Backup (unencrypted) and was able to extract the Chats.
The Photos/Videos show up inline, but some messages does not show with error message: Not supported WhatsApp internal message
See screenshot 1 and see corresponding html code screenshot 2

![Screenshot 2024-03-08 at 17 29 17](https://github.com/KnugiHK/WhatsApp-Chat-Exporter/assets/10906913/f577fcc5-6c23-44fb-b6ad-6fa7769e29a9)

![Screenshot 2024-03-08 at 18 00 46](https://github.com/KnugiHK/WhatsApp-Chat-Exporter/assets/10906913/11e00843-922b-48f5-a678-fa088b855cf7)

**To Reproduce**

Export the chats as in the README

Thanks for providing such a valuable tool.

**Comment by KnugiHK** [comment]
Hi. Can you show me the corresponding message in WhatsApp?

**Comment by mruepp** [comment]
Should be this. But the time is off (10:20 in html vs 11:43 in chat) it is a Video I can not start...
![Screenshot 2024-03-11 at 18 39 47](https://github.com/KnugiHK/WhatsApp-Chat-Exporter/assets/10906913/65e0cb0b-921a-43db-97b5-cc1622e5116c)

**Comment by mruepp** [comment]
Also, btw, is there a way to implement lazy loading? I have chats back to 2014, they are 100-200MB large HTMLs which are nearly unable to load...

**Comment by KnugiHK** [comment]
> Also, btw, is there a way to implement lazy loading? I have chats back to 2014, they are 100-200MB large HTMLs which are nearly unable to load...

There is no lazy loading but you can use `--size 0` to split the chat into multiple files.

**Comment by mruepp** [comment]
Thank you, is there documentation of --size? --size 0 is kind of counterintuitive. What does it mean?

**Comment by KnugiHK** [comment]
> Thank you, is there documentation of --size? --size 0 is kind of counterintuitive. What does it mean?

```
> wtsexporter --help
...
  --size [SIZE], --output-size [SIZE], --split [SIZE]
                        Maximum (rough) size of a single output file in bytes, 0 for auto
```

**Comment by KnugiHK** [comment]
Btw, docs are either located in the [Wiki](https://github.com/KnugiHK/WhatsApp-Chat-Exporter/wiki) or in the help menu.

**Comment by jonx** [comment]
I'm not a web developer but I did some quick research and maybe all we need to get the lazy loading is add a tag to the images as documented here: https://www.w3schools.com/tags/att_img_loading.asp
Only Safari doesn't handle this tag.

`<img src="Media/Profile\33619567857-1665465879.thumb" loading="lazy" class="avatar">`

**Comment by jonx** [comment]
Also while commenting on things that I don't really know, maybe you could consider using the base tag in your HTML? Maybe you have a reason not to use it or maybe it's just me but my links are pretty long like this:
`<a href="AppDomainGroup-group.net.whatsapp.WhatsApp.shared/Media/Profile\6594452603-1709256881.thumb"><img src="AppDomainGroup-group.net.whatsapp.WhatsApp.shared/Media/Profile\6594452603-1709256881.thumb" onerror="this.style.display='none'" class="avatar"></a>`
with the base tag like this:
`<base href="AppDomainGroup-group.net.whatsapp.WhatsApp.shared/">
`
you should be able to shorten the URLs to this:
`<img src="Media/Profile\33619567857-1665465879.thumb">
`

**Comment by KnugiHK** [comment]
> Should be this. But the time is off (10:20 in html vs 11:43 in chat) it is a Video I can not start...

Since you confirmed the video cannot be played, the file in your iPhone probably got corrupted. In this case, I believe it is an isolated case and not the fault of the exporter. Could you find more instances on real media but unspported?

**Comment by KnugiHK** [comment]
If further evidence indicates that the issue is caused by the exporter, please feel free to reopen this issue.
