### ISSUE TITLE
[Please HELP] 'wtsexporter' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by Kazimierz-dev** [KnugiHK/WhatsApp-Chat-Exporter#91]
I'm new to this kind of thing... So, maybe I'm doing something wrong, please help.

**" 'wtsexporter' is not recognized as an internal or external command, operable program or batch file. "**

![image](https://github.com/KnugiHK/WhatsApp-Chat-Exporter/assets/56705684/7afc77e9-a5b9-4745-9ea3-7a986e8217fa)
![image](https://github.com/KnugiHK/WhatsApp-Chat-Exporter/assets/56705684/9f8c28ba-e682-4650-a8d2-889bd52c48c5)
![image](https://github.com/KnugiHK/WhatsApp-Chat-Exporter/assets/56705684/c8825589-0d04-41b2-a81c-9f6c54ef3c25)

Thank you.
# 
- [Android]
- Platform: [Windows]

**Comment by KnugiHK** [comment]
Hi. Did you install it through PIP? It is possible that your PATH environment variable does not includes the script directory of Python.

**Comment by Kazimierz-dev** [comment]
> Hi. Did you install it through PIP? It is possible that your PATH environment variable does not includes the script directory of Python.

Hello. There is no folder directory called "script ". I Will try to reinstall Python tomorrow.

**Comment by KnugiHK** [comment]
The executable path should be like this in Windows: `<root of Python>/Scripts/wtsexporter.exe`

**Comment by Kazimierz-dev** [comment]
> The executable path should be like this in Windows: `<root of Python>/Scripts/wtsexporter.exe`

![image](https://github.com/KnugiHK/WhatsApp-Chat-Exporter/assets/56705684/a1a86084-e7e2-403f-829f-6a111e01acda)
Thanks, now it worked, I think. Now I just need to find out how to visualize, since WhatsApp Viewer isnt working anymore. :-D
